# Generated by Django 5.1.4 on 2026-02-13 04:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, default='')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preco por kg/unidade em R$', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantidade', models.PositiveIntegerField(default=0, help_text='Quantidade em estoque (kg ou unidades)')),
                ('unidade', models.CharField(choices=[('kg', 'Quilograma'), ('un', 'Unidade'), ('cx', 'Caixa')], default='kg', max_length=10)),
                ('data_validade', models.DateField(help_text='Data de validade do lote')),
                ('fornecedor', models.CharField(blank=True, default='', max_length=200)),
                ('estoque_minimo', models.PositiveIntegerField(default=10, help_text='Quantidade minima antes de alertar reposicao')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frutas', to='estoque.categoria')),
            ],
            options={
                'verbose_name': 'Fruta',
                'verbose_name_plural': 'Frutas',
                'ordering': ['nome', 'data_validade'],
            },
        ),
    ]
